Add db-2 task solution
Elaray1/koa-api-starter pull request #1
Opened 2020-07-23 13:48 UTC by Elaray1

2020-07-26 09:06 UTC, paralectvkomodey requested changes

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/list-writers/index.js
> +  });
Не надо делать то, что умеет делать база данных - в приложении.
Конкретно в твоём примере - база данных умеет и сортировать и скипать и в лимиты

Представь, что у тебя в базе лежат данные на 5 ГБ. Даже учитывая, что ты потратишь много времени тупо на пересылку этих данных из сервера, потом ещё и делать это в коде - не самая удачная затея, потому что операции синхронные и ты заблокируешь основной тред node.js. Следовательно всё приложение будет ждать пока пройдёт твой запрос

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/list-writers/index.js
> +  sortBy: Joi.string().valid('createdOn', 'firstName', 'lastName', 'id').default('firstName'),
Вроде как в задании написано, что default - `id`

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/list-writers/index.js
> +  sortBy: Joi.string().valid('createdOn', 'firstName', 'lastName', 'id').default('firstName'),
А разве в mongo документах возвращается ключ `id`? Проверь, пожалуйста

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/list-writers/index.js
> +  const writers = dataArr.splice(pageNumber * documentsInPage, documentsInPage);
Этот handler работает неправильно. В твоём коде сначала берется подмножество документов, а потом уже внутри оно сортируется. В этом нет никакого смысла, потому что я хочу получить первую страницу с отсортированными по убыванию возрастами - а здесь возвращается рандомная страница с документами, но локально отсортированная.

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/list-writers/index.js
> +      numberOfAllDocuments: sortWriters.length,
В твоём случае numberOfAllDocument != количеству всех документов. Оно равно параметру в запросе - documentsInPage. Я и так в курсе, что отправил на сервер, не надо возвращать лишнюю информацию

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/update-writer-book/index.js
> +    ...ctx.validatedData.concat(doc.books),
Всегда, когда есть возможность использовать атомарные методы - их надо использовать. В данном кейсе тебе поможет стандартный оператор $push в MongoDB

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/update-writer-book/index.js
> +  const bookIndex = writer.books.findIndex((el) => el._id === ctx.request.body.bookId);
Код будет неверно работать, если у автора не найдется книги с заданным индексом

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/update-writer-book/index.js
> +  ctx.body = await writerService.update({ _id: ctx.params.id }, () => ({
Если что, callback этого метода принимает один аргумент - doc, который и является документом который ты уже зафетчил заранее через findOne. Соответственно, у тебя лишний запрос в базу(первый)

2020-07-26 09:06 UTC, paralectvkomodey commented on src/resources/writer/writer.schema.js
> +  genre: Joi.string().valid('novel', 'poem').required(),
DRY: book schema у тебя находится в 4х местах

2020-08-06 08:57 UTC, paralectvkomodey requested changes

2020-08-06 08:57 UTC, paralectvkomodey commented on src/resources/writer/list-writers/index.js
> +      numberOfAllDocuments: documentsInPage,
В задании было сказано - количество всех документов по заданной query, а не количество документов на одной странице

2020-08-06 08:57 UTC, paralectvkomodey commented on src/resources/writer/update-writer-book/index.js
> +    books: writer.books.filter((book) => book._id === ctx.request.body.bookId),
Почитай про оператор $pull, умеет всё то же самое, но атомарно

2020-08-06 13:30 UTC, paralectvkomodey requested changes

2020-08-06 13:30 UTC, paralectvkomodey commented on src/resources/writer/update-writer-book/index.js
> +    { $pull: { books: { $in: [ctx.request.body.bookId] } } },
Странное условие. Ты уверен, что такое будет работать?

Вот официальная сигнатура из документации MongoDB: 

`{ $pull: { <field1>: <value|condition>, <field2>: <value|condition>, ... } }`

2020-08-06 13:46 UTC, Elaray1 commented on src/resources/writer/update-writer-book/index.js
> +    { $pull: { books: { $in: [ctx.request.body.bookId] } } },
![image](https://user-images.githubusercontent.com/45394619/89539113-0a26b880-d804-11ea-8922-3272f018a671.png)
![image](https://user-images.githubusercontent.com/45394619/89539159-16127a80-d804-11ea-84e3-8380d5213285.png)
![image](https://user-images.githubusercontent.com/45394619/89539184-1f9be280-d804-11ea-82c0-e1acb16257fa.png)
По этому примеру написал

2020-08-06 13:47 UTC, Elaray1 commented on src/resources/writer/update-writer-book/index.js
> +    { $pull: { books: { $in: [ctx.request.body.bookId] } } },
Пример из официальной документации

2020-08-06 13:49 UTC, Elaray1 commented
А, стоп, там небольшая ошибка

2020-08-09 12:26 UTC, merged